<?php

namespace WebBundle\Repository;

/**
 * CorteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorteRepository extends \Doctrine\ORM\EntityRepository
{
    //funcion que devuelve las tapas para una pagina con un numero de elementos
    public function paginaCortes($pagina=1,$numCortes=3){
        $query = $this->createQueryBuilder('t')
        ->where('t.top = 1')
        ->setFirstResult($numCortes*($pagina-1))
        ->setMaxResults($numCortes)
        ->getQuery();
    return $query->getResult();
    }
}
