<?php

namespace WebBundle\Repository;

/**
 * CorteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorteRepository extends \Doctrine\ORM\EntityRepository
{
}
