<?php

namespace WebBundle\Repository;

/**
 * HerramientaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HerramientaRepository extends \Doctrine\ORM\EntityRepository
{
}
