

welcome:
    path:     /
    defaults: { _controller: WebBundle:Default:homepage } 

web_homepage:
    path:     /{pagina}
    defaults: { _controller: WebBundle:Default:homepage }
    requirements:
        pagina: '\d+' 

nosotros:
    path:     /nosotros
    defaults: { _controller: WebBundle:Default:nosotros }

registro:
    path:     /registro
    defaults: { _controller: WebBundle:Default:registro }

login:
    path:     /login
    defaults: { _controller: WebBundle:Default:login }
    

contactar:
    path:     /contactar/{sitio}
    defaults: { _controller: WebBundle:Default:contactar }

contactar2:
    path:     /contactar
    defaults: { _controller: WebBundle:Default:contactar }

       
nuevaReserva:
    path:     /reservas/nueva/{id}
    defaults: { _controller: WebBundle:GestionReservas:nuevaReserva, id: null } 

borrarReserva:
    path:     /reservas/borrar/{id}
    defaults: { _controller: WebBundle:GestionReservas:borrarReserva, id: null }                  

reservas:
    path:     /reservas/reservas
    defaults: { _controller: WebBundle:GestionReservas:reservas }        


    
corte:
    path:     /corte/{id}
    defaults: { _controller: WebBundle:Default:corte }

corte2:
    path:     /corte
    defaults: { _controller: WebBundle:Default:corte }

nuevoCorte:
    path:     gestioncorte/nuevocorte
    defaults: { _controller: WebBundle:GestionCortes:nuevoCorte }   

gestionReserva:
    path:     gestionreservas/reservas
    defaults: { _controller: WebBundle:GestionCortes:gestionReserva }       


nuevaCat:
    path:     gestioncorte/nuevacategoria
    defaults: { _controller: WebBundle:GestionCortes:nuevaCat }
    
nuevaHerramienta:
    path:     gestioncorte/nuevaherramienta
    defaults: { _controller: WebBundle:GestionCortes:nuevaHerramienta }
    

