services:
    WebBundle\Controller\DefaultController:
      autowire: true # or define your controller constructor and configure its arguments explicitly
      tags: ['controller.service_arguments']
#    web.example:
#        class: WebBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
